In [3]:
import pandas as pd
# A table of data is stored as a pandas DataFrame
# Each column in a DataFrame is a Series

In [19]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['c0','c1','c2']
                 , index=['r0','r1','r2'], )
df[['c1','c2']]
# df

    c1  c2
r0   2   3
r1   5   6
r2   8   9

In [4]:
obesity_data = pd.read_csv("obesity_prediction.csv")
obesity_data.head()
obesity_data.tail(10)
obesity_data.sample(12, random_state=23)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2,Male,23.000000,1.800000,77.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
1759,Male,30.945369,1.759647,120.009392,yes,yes,2.766612,3.000000,Sometimes,no,2.173417,no,1.089344,1.198439,Sometimes,Automobile,Obesity_Type_II
1031,Female,18.863875,1.560029,71.728069,yes,no,3.000000,3.339914,Sometimes,no,2.000000,no,1.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_II
1239,Female,23.000000,1.610820,82.532994,yes,yes,2.096630,2.879541,Sometimes,no,2.432967,no,1.887012,0.000000,no,Public_Transportation,Obesity_Type_I
1191,Male,23.335391,1.713380,82.085549,yes,yes,2.716909,2.598079,Sometimes,no,2.905450,no,1.600431,0.176892,Sometimes,Public_Transportation,Overweight_Level_II
852,Female,21.016623,1.755427,78.300084,yes,yes,3.000000,1.000000,Sometimes,no,2.000000,no,2.877473,0.000000,Sometimes,Public_Transportation,Overweight_Level_I
1502,Male,27.968765,1.673767,89.995034,yes,yes,1.961069,3.000000,Sometimes,no,2.652327,no,0.569310,0.319008,Sometimes,Automobile,Obesity_Type_I
1232,Male,31.315593,1.673352,90.000000,yes,yes,2.190110,2.029858,Sometimes,no,2.348981,no,1.946907,0.000000,Sometimes,Automobile,Obesity_Type_I
64,Female,21.000000,1.660000,57.000000,yes,yes,2.000000,3.000000,Frequently,no,1.000000,no,1.000000,1.000000,no,Public_Transportation,Normal_Weight
986,Female,28.583944,1.578560,65.522744,yes,no,2.000000,2.283673,Sometimes,no,1.970622,no,1.863258,1.581703,Sometimes,Public_Transportation,Overweight_Level_II
897,Male,26.703710,1.802871,85.770013,yes,yes,2.872121,3.051804,Sometimes,no,2.111913,no,0.843709,0.153559,Sometimes,Automobile,Overweight_Level_I
752,Male,21.142432,1.855353,86.413388,yes,yes,2.000000,3.000000,Sometimes,no,1.345298,no,1.097905,1.000000,Sometimes,Public_Transportation,Overweight_Level_I

In [44]:
# obesity_data.index
# obesity_data.size
obesity_data.describe()
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [9]:
obesity_data = obesity_data.set_index("Height")
obesity_data

,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
Height,,,,,,,,,,,,,
1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation
1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation
1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation
1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking
1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation
1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation
1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation
1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation
1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation