In [2]:
import pandas as pd
# A table of data is stored as a pandas DataFrame
# Each column in a DataFrame is a Series

In [19]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['c0','c1','c2']
                 , index=['r0','r1','r2'], )
df[['c1','c2']]
# df

    c1  c2
r0   2   3
r1   5   6
r2   8   9

In [24]:
obesity_data = pd.read_csv("obesity_prediction.csv")
obesity_data.head()
obesity_data.tail(10)
obesity_data.sample(12)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
1838,Female,20.989016,1.807340,155.872093,yes,yes,3.000000,3.000000,Sometimes,no,2.417122,no,0.952725,0.573958,Sometimes,Public_Transportation,Obesity_Type_III
2038,Female,26.000000,1.608283,105.359688,yes,yes,3.000000,3.000000,Sometimes,no,2.476002,no,0.000000,0.546345,Sometimes,Public_Transportation,Obesity_Type_III
1380,Male,39.685846,1.781032,96.303855,yes,yes,2.252698,2.475228,Sometimes,no,2.923856,no,2.165429,0.616045,Frequently,Automobile,Obesity_Type_I
555,Male,18.000000,1.753349,51.457226,no,yes,2.823179,3.000000,Sometimes,no,1.773236,no,1.252472,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
934,Male,19.576682,1.834715,89.429199,yes,yes,2.342323,3.608850,Sometimes,no,2.878866,no,2.000000,0.208323,Sometimes,Public_Transportation,Overweight_Level_I
632,Female,19.000000,1.540375,42.006282,no,no,2.938031,2.705445,Frequently,no,1.333807,yes,1.877369,0.370973,Sometimes,Public_Transportation,Insufficient_Weight
436,Female,18.000000,1.560000,55.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,0.000000,0.000000,Frequently,Automobile,Normal_Weight
2068,Female,24.196367,1.697421,114.482386,yes,yes,3.000000,3.000000,Sometimes,no,2.909675,no,0.360908,0.573887,Sometimes,Public_Transportation,Obesity_Type_III
378,Male,18.000000,1.730000,70.000000,no,yes,3.000000,3.000000,Frequently,no,1.000000,no,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
1214,Female,25.706285,1.585547,80.351263,yes,yes,2.000000,1.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Obesity_Type_I
1519,Male,26.945139,1.773259,118.154345,yes,no,2.183540,3.000000,Sometimes,no,2.277937,no,0.681830,0.000000,Sometimes,Automobile,Obesity_Type_II
2033,Female,26.000000,1.643017,111.720238,yes,yes,3.000000,3.000000,Sometimes,no,2.632498,no,0.000000,0.140792,Sometimes,Public_Transportation,Obesity_Type_III